### ISSUE TITLE
Missing plot in the Differential Expression analysis

### ISSUE THREAD

**Issue by GianniNigita** [knowmics-lab/tRFUniverse#4]
In all the tries I made for the Differential Expression analysis, the plot "expression vs. group" (the one on the right in the image below) was not produced:
![Screenshot 2024-07-22 at 7 11 01 AM](https://github.com/user-attachments/assets/1d818a3a-2d45-49d1-a646-10ae62325290)

Also, when I tried to download the plots ("volcano" and "expression vs. group" plots), either png or svg formats, via the "Save Plot" button, it does not download them.

**Comment by GianniNigita** [comment]
I tried selecting one tRF fragment, and the graph was generated (please see below). However, the second issue about downloading both plots is still present.
![Screenshot 2024-07-22 at 9 27 46 AM](https://github.com/user-attachments/assets/db9571cf-5fb9-4fa5-9d21-503bddaea498)

**Comment by alaimos** [comment]
The issue cannot be reproduced. The issue might be caused by browser plugins or network security policy.
